# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.IntegerField(default=0)),
                ('n_rg', models.IntegerField()),
                ('n_cpf', models.IntegerField()),
                ('placa_carro', models.CharField(max_length=200)),
                ('num_serie', models.IntegerField()),
            ],
        ),
    ]
