# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxista',
            old_name='n_cpf',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='taxista',
            old_name='n_rg',
            new_name='rg',
        ),
    ]
