# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxistas', '0003_taxista_ddd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxista',
            old_name='ddd',
            new_name='DDD',
        ),
    ]
