# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxistas', '0005_auto_20161127_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxista',
            old_name='numero_de_serie_aparelho_integrato',
            new_name='Serial_numberd_do_aparelho_integrato',
        ),
    ]
