# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxistas', '0008_taxista_marca_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxista',
            name='DDD',
            field=models.IntegerField(default=51),
        ),
        migrations.AlterField(
            model_name='taxista',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
