# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxistas', '0002_auto_20161119_0341'),
        ('investimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='taxista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxistas.Taxista'),
        ),
    ]
