# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0002_investimento_taxista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='numero_integrantes',
        ),
        migrations.AddField(
            model_name='investimento',
            name='outros_gastos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='investimento',
            name='valor_IPVA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='investimento',
            name='valor_seguro',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='combustivel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='valor_combustivel',
            field=models.FloatField(default=0),
        ),
    ]
