# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0003_auto_20161201_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='combustivel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='outros_gastos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='valor_IPVA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='valor_combustivel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='valor_seguro',
            field=models.FloatField(),
        ),
    ]
