# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0004_auto_20161201_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='dia_investimento',
            field=models.DateField(null=True),
        ),
    ]
