# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0005_investimento_dia_investimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investimento',
            old_name='dia_investimento',
            new_name='data_investimento',
        ),
    ]
