# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_corrida', models.DateField()),
                ('endereco_inicial', models.CharField(max_length=200)),
                ('endereco_final', models.CharField(max_length=200)),
                ('horario_partida', models.TimeField(blank=True, null=True)),
                ('horario_chegada', models.TimeField(blank=True, null=True)),
                ('distancia', models.FloatField()),
                ('valor', models.FloatField()),
                ('dinheiro', models.BooleanField(default=False)),
                ('cartao', models.BooleanField(default=False)),
                ('taxista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxistas.Taxista')),
            ],
        ),
    ]
