# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corrida',
            old_name='endereco_final',
            new_name='endereco_destino',
        ),
        migrations.RenameField(
            model_name='corrida',
            old_name='endereco_inicial',
            new_name='endereco_origem',
        ),
    ]
